#! /usr/bin/python3
import os
import time
import serial#pyserial

def waitFor(target,dev,display=True):#avoid loss data
	msgs=''
	while True:
		cnt=dev.inWaiting()
		if cnt>0:
			msg=dev.read(cnt).decode()
			msgs=msgs+msg
			if display:
				print(msg,end='')
			if msgs.find(target)!=-1:
				return

def dumpImg(dev,k_addr='0xa0000',kernel='kernel87.img'):
	k_size=os.stat(kernel).st_size

	waitFor(': ',dev)
	dev.write(str.encode(k_addr+'\n'))

	waitFor(': ',dev)
	dev.write(str.encode(str(k_size)+'\n'))

	with open(kernel,"rb") as f:
		waitFor('...\r\n',dev)
		for i in range(k_size):
			dev.write(f.read(1))
			waitFor('.',dev,False)

def getLine(file):
	cmd=f.readline()
	if cmd=='':
		cmd=input('\n(Relay)');
		cmd=cmd+'\n'
	return cmd


if __name__=='__main__':
	src=input('src(\'/dev/ttyUSB0\')?')
	br=115200
	dev=serial.Serial(src,br)

	test_case='./input'
	f=open(test_case,'r')
	while True:
		#input
		cmd=getLine(f)
		dev.write(str.encode(cmd))
		if cmd=='loadimg\n':
			k_addr=getLine(f)
			kernel=getLine(f)
			dumpImg(dev,k_addr=k_addr[:-1],kernel=kernel[:-1])
		elif cmd=='archive\n' or cmd=='falloc\n' or cmd=='ffree\n':
			waitFor(': ',dev)
			name=getLine(f)
			dev.write(str.encode(name))

		#output
		waitFor('$ ',dev)