#! /bin/bash
BUILD_DIR=build
CMAKE_DIR=$BUILD_DIR/tmp

## clean
if [ "$1" == "-c" ]
then
    rm -rf build
fi

mkdir -p $BUILD_DIR

# build in CMAKE_DIR
cmake -S . -B $CMAKE_DIR -DDEBUG=ON &&
cd $CMAKE_DIR
make &&

cd ../../
aarch64-linux-gnu-objcopy $CMAKE_DIR/bootloader/bootloader.elf -O binary $BUILD_DIR/bootloader.img
aarch64-linux-gnu-objcopy $CMAKE_DIR/kernel/kernel8.elf -O binary $BUILD_DIR/kernel8.img
aarch64-linux-gnu-objcopy $CMAKE_DIR/app/app.elf -O binary assets/rootfs/app
aarch64-linux-gnu-objcopy $CMAKE_DIR/argv_test/argv_test.elf -O binary assets/rootfs/argv_test
aarch64-linux-gnu-objcopy $CMAKE_DIR/fork_test/fork_test.elf -O binary assets/rootfs/fork_test

# copy to build
cd assets/rootfs
find . | cpio -o -H newc > ../../$BUILD_DIR/initramfs.cpio

