[package]
authors = ["Ian Chen <ianre657@gmail.com>"]
edition = "2018"
name = "impl-rs"
version = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
