extern void delay ( unsigned long);
extern void put32 ( unsigned long, unsigned int );
extern unsigned int get32 ( unsigned long );
extern void branch_to_address(char *dt, char *addr);
extern void _branch_to_address(unsigned long addr);
extern int lead_zero(int num);
extern unsigned int get_el(void);
extern unsigned int get_sctlr_el1(void);
extern unsigned long get_hcr_el2(void);
extern unsigned int get_scr_el3(void);
extern unsigned int get_spsr_el2(void);
extern unsigned int get_cntfrq_el0(void);
extern unsigned long set_user_program(char *start, char *usp, int argc, char**argv, char *ksp_reset_location);
extern void to_el0(void);
extern void run_sighand(unsigned long handler, char *sigaltstack, unsigned long sigtramp_addr);
extern unsigned long get_x8(void);
extern void enable_irq(void);
extern void disable_irq(void);
extern void core_timer_enable(void);
extern void core_timer_disable(void);
extern void wait_for_interrupt(void);
extern void set_ttbr1(unsigned long* kpgd);
extern void set_ttbr0(unsigned long* pgd);
extern void _set_ttbr0(unsigned long* pgd);