int strcmp(char*, char*);
int strlen (char*);
void my_shell();
void command();
void command_help();
void command_hello();
void command_reboot();
void command_notfound();
void command_cpio();
void command_cpiols();