#ifndef _BOOTLOADER_H
#define _BOOTLOADER_H

#define BOOTLOADER_ORIGNINAL_ADDRESS (0x80000)
#define BOOTLOADER_ORIGINAL_STACK_TOP (0xC0000)

#define BOOTLOADER_RELOCATED_ADDRESS (0x60000)
#define BOOTLOADER_RELOCATED_STACK_TOP (0xA0000)

#endif